#!/bin/env bash
black="\e[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
background="\033[0m"
token="\u0037\u0037\u0038\u0037\u0030\u0036\u0034\u0034\u0066\u0061\u0032\u0033\u0063\u0031"
GithubMirror="https://mirrors.chenby.cn/"

function MenuTips(){
  echo "当前时期 $(date +"%Y-%m-%d %H:%M")"
}

function ErrorReturn(){
echo -en "
${white}————————————————————
    脚本运行出现${red}错误$white,请及时${blue}截图${white},保存报错信息,
    以与便开发者,${green}更好的${white}和${green}更快的${cyan}解决${white}问题.
${white}————————————————————${background}"
read
return 1
}

function gitclone(){
if [ -d $2 ]
then
  echo -e ${red}目标路径已经存在${background}
  return 1
fi
if echo $1 | grep -q gitee
then
  git clone --depth=1 $1 $2
  return 0
fi
if CheckNetwork
then
  MirrorNum=("gh" "ghproxy" "kkgithub" "github" "error")
else
  MirrorNum=("github")
fi
for i in ${MirrorNum[@]}
do
  case ${i} in
  github)
    if git clone --depth=1 $1 $2
    then
      return 0
    else
      rm -rf $2
    fi
    ;;
  gitclone)
    GitUrl=$(echo $1 | sed 's|https://github.com|https://gitclone.com/github.com|g')
    if git clone --depth=1 ${GitUrl} $2
    then
      return 0
    else
      rm -rf $2
    fi
    ;;
  kkgithub)
    GitUrl=$(echo $1 | sed 's|https://github.com|https://kkgithub.com|g')
    if git clone --depth=1 ${GitUrl} $2
    then
      return 0
    else
      rm -rf $2
    fi
    ;;
  gh)
    GitUrl=$(echo $1 | sed 's|https://github.com|https://gh.arcticfox.top/https://github.com|g')
    if git clone --depth=1 ${GitUrl} $2
    then
      return 0
    else
      rm -rf $2
    fi
    ;;
  ghproxy)
    GitUrl=$(echo $1 | sed 's|https://github.com|https://mirror.ghproxy.com/https://github.com|g')
    if git clone --depth=1 ${GitUrl} $2
    then
      return 0
    else
      rm -rf $2
    fi
    ;;
  error)
    echo -e ${yellow}仓库克隆 ${red}失败${background}
    exit 1
    ;;
  esac
done
}

function Download(){
file="$1"
URL="$2"
local i=0
if wget --help | grep -q show-progress 
then
  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
  until wget -q --show-progress -O ${file} -c ${URL}
  do
    if [ ${i} == 3 ]
    then
      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
      return 1
    fi
    i=$((${i}+1))
    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成.${background}
  return 0
else
  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
  until wget -O ${file} -c ${URL}
  do
    if [ ${i} == 3 ]
    then
      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
      return 1
    fi
    i=$((i+1))
    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成.${background}
  return 0
fi
}

function MenuSize(){
local HEIGHT=$(($(tput lines) - 5))
local WIDTH=$(($(tput cols) - 5))
local OPTION=$((${HEIGHT} - 7))
if (( $HEIGHT <= 3 ));then
  echo -e ${blue}[${red}*${blue}] ${cyan}您的屏幕高度过低.${background}
  echo -e ${blue}[${red}*${blue}] ${cyan}考虑缩小终端字体.${background}
  exit
fi
if (( $WIDTH <= 0 ));then
  echo -e ${blue}[${red}*${blue}] ${cyan}您的屏幕宽度度过窄.${background}
  echo -e ${blue}[${red}*${blue}] ${cyan}考虑缩小终端字体.${background}
  exit
fi
echo ${HEIGHT} ${WIDTH} ${OPTION}
}

function MsgboxSize(){
local HEIGHT=$(($(tput lines) - 15))
local WIDTH=$(($(tput cols) - 5))
if (( $HEIGHT <= 0 ));then
  echo -e ${blue}[${red}*${blue}] ${cyan}您的屏幕高度过低.${background}
  echo -e ${blue}[${red}*${blue}] ${cyan}考虑缩小终端字体.${background}
  exit
fi
if (( $WIDTH <= 0 ));then
  echo -e ${blue}[${red}*${blue}] ${cyan}您的屏幕宽度度过窄.${background}
  echo -e ${blue}[${red}*${blue}] ${cyan}考虑缩小终端字体.${background}
  exit
fi
echo ${HEIGHT} ${WIDTH}
}

Arch(){
case $1 in
1)
  case `uname -m` in
  aarch64|arm64)
  	echo arm64
  	;;
  x86_64|x64|amd64)
  	echo amd64
  	;;
  *)
  	echo -e ${red}暂不支持的架构 ${cyan}$(dpkg --print-architecture)${background}
  	until read
  	do
  	  echo -e ${red}暂不支持的架构 ${cyan}$(dpkg --print-architecture)${background}
  	done
  	;;
  esac
;;
2)
  case `uname -m` in
  aarch64|arm64)
  	echo arm64
  	;;
  x86_64|x64|amd64)
  	echo x64
  	;;
  *)
  	echo -e ${red}暂不支持的架构 ${cyan}$(uname -m)${background}
  	while read
  	do
  	  echo -e ${red}暂不支持的架构 ${cyan}$(uname -m)${background}
  	done
  	;;
  esac
;;
3)
  case `uname -m` in
  aarch64|arm64)
  	echo aarch64
  	;;
  x86_64|x64|amd64)
  	echo amd64
  	;;
  *)
    echo -e ${red}暂不支持的架构 ${cyan}$(uname -m)${background}
  	while read
  	do
  	  echo -e ${red}暂不支持的架构 ${cyan}$(uname -m)${background}
  	done
  	;;
  esac
;;
4)
  case `uname -m` in
  aarch64|arm64)
  	echo aarch64
  	;;
  x86_64|x64|amd64)
  	echo x64
  	;;
  *)
  	echo -e ${red}暂不支持的架构 ${cyan}$(uname -m)${background}
  	while read
  	do
  	  echo -e ${red}暂不支持的架构 ${cyan}$(uname -m)${background}
  	done
  	;;
  esac
;;
esac
}

function ErrorReturn(){
echo -en "
${white}————————————————————
    脚本运行出现${red}错误$white,请及时${blue}截图${white},保存报错信息,
    以与便开发者,${green}更好的${white}和${green}更快的${cyan}解决${white}问题.
${white}————————————————————${background}"
read
}

function SelectRegion(){
function Tips(){
echo && echo -en " ${cyan}Yunzai ${purple}一键安装管理脚本${background}
 ———————————————————
 ${cyan}请问您的设备所在位置是? 
    ${green}1${white}. 中国大陆 ${background}
    ${green}2${white}. 其他位置 ${background}
 ———————————————————
 ${cyan}请输入数字 ${white}[1-2]:${background} "
}
 read -p "$(Tips)" num
 case ${num} in
 1)
  return 0
  ;;
 2)
  return 1
  ;;
 *)
  echo -e ${red}输入错误 ${yellow}将保持默认 ${purple}中国大陆${background}
  return 0
  ;;
  esac
}

function CheckNetwork(){
IpinfoIo=$(curl -sL ipinfo.io/json)
if [ -z "${IpinfoIo}" ]
then
  if SelectRegion
  then
    return 0
  else
    return 1
  fi
else
  if echo ${IpinfoIo} | grep -q error
  then
    token=$(echo -e ${token})
    if curl -sL ipinfo.io/json?token=${token} | jq .country | grep -q "CN"
    then
      return 0
    else
      return 1
    fi
  else
    if echo ${IpinfoIo} | jq .country | grep -q "CN"
    then
      return 0
    else
      return 1
    fi
  fi
fi
}

function Update(){
if [ -z ${Update} ]
then
  Command=$@
  ${Command}
  Update=true
fi
}

function TUISoftware(){
if [ -x "$(command -v whiptail)" ];then
  echo whiptail
elif [ -x "$(command -v dialog)" ];then
  echo dialog
else
  echo -e ${red}没有TUI软件${background}
  exit 1
fi
}

function Session(){
  jq .SelectManageSession $AFNTQQHOME/config.json | sed 's|"||g'
}

function StopBot(){
CheckStatus $1 $2
case $? in
1)
  if ManageSession tmux stop $1
  then
    return 0
  else
    return 1
  fi
  ;;
2)
  if ManageSession screen stop $1
  then
    return 0
  else
    return 1
  fi
  ;;
3)
  PID=$(ps all | sed '/grep/d' | sed '/dialog/d' | sed '/whiptail/d' | grep $2 | awk '{print $1}')
  kill -9 ${PID}
  ;;
esac
}

function RestartBot(){
CheckStatus $1 $2
case $? in
1)
  if ManageSession tmux restart $1
  then
    return 0
  else
    return 1
  fi
  ;;
2)
  if ManageSession screen restart $1
  then
    return 0
  else
    return 1
  fi
  ;;
3)
  PID=$(ps all | sed '/grep/d' | sed '/dialog/d' | sed '/whiptail/d' | grep $2 | awk '{print $1}')
  kill -9 ${PID}
  START $1 $3
  ;;
esac
}

function LogBot(){
CheckStatus $1 $2
case $? in
1)
  if ManageSession tmux log $1
  then
    return 0
  else
    return 1
  fi
  ;;
2)
  if ManageSession screen log $1
  then
    return 0
  else
    return 1
  fi
  ;;
3)
  echo $1 [前台] 启动
  return 1
  ;;
esac
}

function PsAll(){
  ps all | sed '/grep/d' | sed '/dialog/d' | sed '/whiptail/d' | grep -q $1
}

function CheckStatus(){
if tmux ls 2>&1 | grep -q $1
then
  return 1
elif screen -ls 2>&1 | grep -q $1
then
  return 2
elif PsAll $2
then
  return 3
else
  return 0
fi
}

function StartType(){
CheckStatus $1 $2
case $? in
1)
  $(TUISoftware) --title "AF-IdentifyType" \
  --msgbox "$3 已在 [Tmux] 中启动" \
  $(MsgboxSize)
  return 1
;;
2)
  $(TUISoftware) --title "AF-IdentifyType" \
  --msgbox "$3 已在 [Screen] 中启动" \
  $(MsgboxSize)
  return 2
;;
3)
  $(TUISoftware) --title "AF-IdentifyType" \
  --msgbox "$3 已在 [前台] 中启动" \
  $(MsgboxSize)
  return 3
;;
esac
}

function ManageSession(){
case $1 in
tmux)
  case $2 in
    start)
      if tmux new -s $3 -d "$4" > /dev/null
      then
        return 0
      else
        return 1
      fi
    ;;
    stop)
      if tmux kill-session -t $3 > /dev/null
      then
        return 0
      else
        return 1
      fi
    ;;
    restart)
      if tmux kill-session -t $3 && tmux new -s $3 -d "$4" > /dev/null
      then
        return 0
      else
        return 1
      fi
    ;;
    log)
      if tmux attach -t $3 > /dev/null
      then
        return 0
      else
        return 1
      fi
    ;;
    list)
      if tmux ls | grep -q $3
      then
        return 0
      else
        return 1
      fi
    ;;
  esac
;;
screen)
  case $2 in
    start)
      if screen -S $3 -d -m bash -c "$4"
      then
        return 0
      else
        return 1
      fi
      ;;
    stop)
      Session=$(screen -ls | grep $3 | awk '{print $1}')
      if screen -X -S ${Session} quit
      then
        return 0
      else
        return 1
      fi
      ;;
    restart)
      Session=$(screen -ls | grep $3 | awk '{print $1}')
      if screen -X -S ${Session} quit && screen -S ${Session} -d -m bash -c "$4"
      then
        return 0
      else
        return 1
      fi
      ;;
    log)
      Session=$(screen -ls | grep $3 | awk '{print $1}')
      if screen -r ${Session}
      then
        return 0
      else
        return 1
      fi
      ;;
    list)
      if screen -ls | grep -q $3
      then
        return 0
      esle
        return 1
      fi
      ;;
  esac
;;
esac
}

function START(){
  local Command="$1"
  ${Command}
  echo -e ${cyan}回车返回${background}
}

function ProgressBar(){
  {
    i=0
    while CheckStatus $1 $2
    do
      echo $((i++))
      if echo ${i} | grep -q 100
      then
        return 1
      fi
    done
    return 0
  } | $(TUISoftware) --gauge "$1 [正在启动]" $(MsgboxSize) 0
}

function CheckPath(){
  if [ -e "$1" ]
  then
    return 0
  else
    return 1
  fi
}

function CheckInstall(){
  case $1 in
  NapCat)
    if CheckPath "/opt/QQ/resources/app/app_launcher/napcat/napcat.mjs"
    then
      return 0
    else
      return 1
    fi
    ;;
  esac
}